RED="\e[31m"
ORANGE="\e[33m"
BLUE="\e[94m"
GREEN="\e[92m"
STOP="\e[0m"
RED="$(printf '\033[31m')"  GREEN="$(printf '\033[32m')"  ORANGE="$(printf '\033[33m')"  BLUE="$(printf '\033[34m')"
MAGENTA="$(printf '\033[35m')"  CYAN="$(printf '\033[36m')"  WHITE="$(printf '\033[37m')" BLACK="$(printf '\033[30m')"
REDBG="$(printf '\033[41m')"  GREENBG="$(printf '\033[42m')"  ORANGEBG="$(printf '\033[43m')"  BLUEBG="$(printf '\033[44m')"
MAGENTABG="$(printf '\033[45m')"  CYANBG="$(printf '\033[46m')"  WHITEBG="$(printf '\033[47m')" BLACKBG="$(printf '\033[40m')"
RESETBG="$(printf '\e[0m\n')"
printf "${GREEN}"
printf "=================================\n"
printf "${ORANGE}"
figlet -w 200 -f standard "WHITE          DEVIL"
printf "${BLUE}"
figlet -w 200 -f  big ".                 ..    GS    ..              ."
printf "${GREEN}"
printf "=================================\n"
printf "${STOP}"
echo "  "
echo "[+] --- Loading Tools"

sleep 2
clear
printf "${GREEN}"
printf "=================================\n"
printf "${ORANGE}"
figlet -w 200 -f standard "WHITE          DEVIL"
printf "${BLUE}"
figlet -w 200 -f  big ".                 ..    GS    ..              ."
printf "${GREEN}"
printf "=================================\n"
printf "${STOP}"
echo "${RED}[${WHITE}01${RED}]${ORANGE}- IP        ${RED}[${WHITE}04${RED}]${ORANGE}- Domain     "
echo "${RED}[${WHITE}02${RED}]${ORANGE}- SSL       ${RED}[${WHITE}05${RED}]${ORANGE}- Href Links "
echo "${RED}[${WHITE}03${RED}]${ORANGE}- Title     ${RED}[${WHITE}06${RED}]${ORANGE}- All"
echo "${RED}[${WHITE}99${RED}]${ORANGE}- Exit"

sudo python3 main.py 


